# Generated by Django 4.1.3 on 2022-11-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_products_image_src"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Orders",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
